name: COMPRESSION-DECOMPRESSION WORKFLOW

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install GCC
      - name: Install GCC
        run: sudo apt-get install -y gcc

      # Step 3: Compile the C program
      - name: Compile the C program
        run: gcc -o projetc_fv projetc_fv.c

      # Step 4: Create a test file for compression
      - name: Create a test file for compression
        run: echo "this is a test text for compression." > testcase.txt

      # Step 5: Run the program for compression
      - name: Run the program for compression
        run: |
          echo "1" | ./projetc_fv
        env:
          INPUT_FILE: testcase.txt

      # Step 6: Check if the compressed file is created
      - name: Check if the compressed file is created
        run: |
          if [ ! -f "testcase_compressed.txt" ]; then
            echo "Compression failed."
            exit 1
          fi

      # Step 7: Run the program for decompression
      - name: Run the program for decompression
        run: |
          echo "2" | ./projetc_fv
        env:
          INPUT_FILE: testcase_compressed.txt

      # Step 8: Check if the decompressed file is created
      - name: Check if the decompressed file is created
        run: |
          if [ ! -f "testcase_decompressed.txt" ]; then
            echo "Decompression failed."
            exit 1
          fi
