name: COMPRESSION-DECOMPRESSION WORKFLOW

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Update package list
      - name: Update package list
        run: sudo apt-get update

      # Step 3: Install GCC
      - name: Install GCC
        run: sudo apt-get install -y gcc

      # Step 4: Compile the C program
      - name: Compile the C program
        run: gcc -o projetc_fv projetc_fv.c

      # Step 5: Create a test file for compression
      - name: Create a test file for compression
        run: echo "this is a test text for compression." > testcase.txt

      # Step 6: Run the program for compression
      - name: Run the program for compression
        run: ./projetc_fv testcase.txt

      # Step 7: Check if the compressed file is created
      - name: Check if the compressed file is created
        run: |
          if [ ! -f "testcase_compressed.txt" ]; then
            echo "Compression failed."
            exit 1
          fi

      # Step 8: Debug: Print compressed file content
      - name: Debug: Print compressed file content
        run: cat testcase_compressed.txt

      # Step 9: Run the program for decompression
      - name: Run the program for decompression
        run: ./projetc_fv testcase_compressed.txt

      # Step 10: Check if the decompressed file is created
      - name: Check if the decompressed file is created
        run: |
          if [ ! -f "testcase_decompressed.txt" ]; then
            echo "Decompression failed."
            exit 1
          fi

      # Step 11: Debug: Print original file content
      - name: Debug: Print original file content
        run: cat testcase.txt

      # Step 12: Debug: Print decompressed file content
      - name: Debug: Print decompressed file content
        run: cat testcase_decompressed.txt

      # Step 13: Debug: Hexdump files to find byte-level differences
      - name: Debug: Hexdump files
        run: |
          echo "Hexdump original file:"
          hexdump -C testcase.txt
          echo "Hexdump decompressed file:"
          hexdump -C testcase_decompressed.txt

      # Step 14: Verify decompressed content matches original
      - name: Verify decompressed content
        run: |
          cmp --silent testcase.txt testcase_decompressed.txt || (echo "Files differ!" && exit 1)

      # Step 15: Final success message
      - name: Success message
        run: echo "Compression and decompression workflow completed successfully!"
